services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    #volumes:
      #- ./frontend/dist:/app/src/main/resources/static  # or copy during build
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/reactumlapp


  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: reactumlapp

