services:
  backend:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/reactumlapp

  frontend:
    command: npm run dev  # Start Vite dev server

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reactumlapp
